api:
  image: sstarcher/sensu
  command: api
  links:
    - rabbitmq
    - redis
  volumes:
    - ./check.d:/etc/sensu/check.d
  environment:
    RABBITMQ_PORT: 5672
server:
  image: sstarcher/sensu
  command: server
  links:
    - rabbitmq
    - redis
    - api
  volumes:
    - ./check.d:/etc/sensu/check.d
    - ./handlers:/etc/sensu/handlers
    - ./extensions:/etc/sensu/extensions
  environment:
    RABBITMQ_PORT: 5672
uchiwa:
  image: sstarcher/uchiwa
  links:
    - api:sensu
  ports:
    - '80:3000'
rabbitmq:
  image: rabbitmq:3.5-management
  ports:
    - '5672:5672'
redis:
  image: redis
  volumes:
    - /srv/redis:/data
influxdb:
  image: tutum/influxdb:latest
  volumes:
    - /srv/influxdb:/data
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "8089:8089/udp"
  environment:
    PRE_CREATE_DB: sensu
    UDP_DB: sensu
    UDP_PORT: 8089
    COLLECTD_DB: collectd
grafana:
  image: grafana/grafana:latest
  ports:
    - "3000:3000"
  links:
    - influxdb
collectd:
  build: ../collectd
  volumes:
    - ../collectd/conf.d:/etc/collectd/collectd.conf.d
    - /srv/collectd:/var/lib/collectd
  links:
    - influxdb
